### ISSUE TITLE
ID field in admin 

### ISSUE THREAD

**Issue by gurugeek** [samirelanduk/django-random-id-model#1]
thanks for your package. I did as per readme 👍 

```
from django_random_id_model import RandomIDModel

class Work(RandomIDModel):
	title = models.CharField(max_length=200)
	body = HTMLField()
	published = models.BooleanField(default=False, null=True)
	date = models.DateTimeField(auto_now=True)
```

the problem is that now in adming (or add forms) an ID is required so I need to enter it mantually?
I am confident that this was not interended behaviour so thanks in advance for your help!

**Comment by samirelanduk** [comment]
Hi - sorry this is an issue I came across too, I just forgot to add the solution to the README. You just need to to exclude the field in the ModelForm:

```python
class WorkForm(ModelForm):

    class Meta:
        model = Work
        exclude = ["id"]
```

This should make the form work properly. I haven't used the RandomIDModel with django admin yet, but I suspect this should make it work there too.

If you can confirm this fixes it, I will update the README.

**Comment by gurugeek** [comment]
thanks for your prompt reply, this fixes it for the forms mode (class meta) l but how to handle it in admin ? it still shows if I add it via admin

**Comment by samirelanduk** [comment]
Hmmm - it's been a while since I've used admin in depth, but I believe you can specify fields to be excluded there too, using [something like this](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.exclude). I think if you exclude the id field there too it should work with admin too.

**Comment by gurugeek** [comment]
thanks for the reminder, yes this works fine so for admin you need something like 

```
class WorkAdmin(admin.ModelAdmin):
	exclude = ('id',)

admin.site.register(Work,WorkAdmin)
```
thanks again for this very useful package, much appreciated. The django UUID always had some issues!
