### ISSUE TITLE
what if i set ID_DIGITS_LENGTH=1 and create 9 objects, what will happen after than?

### ISSUE THREAD

**Issue by na5imuzzaman** [samirelanduk/django-random-id-model#2]

**Comment by samirelanduk** [comment]
Once all available digits have been used up, trying to create new objects will get stuck in an infinite loop as it constantly searches for an unused ID, never finding one. Not recommended!

**Comment by na5imuzzaman** [comment]
any solution?

**Comment by na5imuzzaman** [comment]
is there any possible way to pragmatically increase  ID_DIGITS_LENGTH value?

**Comment by samirelanduk** [comment]
You can just change it in settings.py - it won’t change the IDs of existing objects but new objects created will have IDs with more digits.

**Comment by na5imuzzaman** [comment]
okay. thank you
