### ISSUE TITLE
Use PositiveBigIntegerField instead of BigIntegerField

### ISSUE THREAD

**Issue by pakal** [samirelanduk/django-random-id-model#3]
Nice module, thanks !

Some fixture generators like Django-Baker will prefill this ID with random negative values, breaking e.g. URL resolution (because it expects a positive integer in the regex of <int> placeholders of URLs)

So the simplest would be to use PositiveBigIntegerField, also allowing tiny optimizations at DB level maybe.

(Of course this can still be overridden at subclass level, so it's not very blocking)

**Comment by samirelanduk** [comment]
Yeah this is better I think - thanks.
